// <auto-generated />
using System;
using BlackJackCheater.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlackJackCheater.Migrations
{
    [DbContext(typeof(BlackJackDbContext))]
    partial class BlackJackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("BlackJackCheater.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("IdMatch")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Occurences")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMatch");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("BlackJackCheater.Models.Match", b =>
                {
                    b.Property<string>("IdMatch")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumberOfUsers")
                        .HasColumnType("int");

                    b.HasKey("IdMatch");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("BlackJackCheater.Models.Card", b =>
                {
                    b.HasOne("BlackJackCheater.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("IdMatch");

                    b.Navigation("Match");
                });
#pragma warning restore 612, 618
        }
    }
}
